from .ast import Assign, Binary, BinaryOp, Comp, Decl, Identifier, Mod, UnaryOp


# Dict of First Sets used to enter syntactical rules
FIRST_SETS = {
    'comp': ['main', 'comp'],
    'stmt': ['in', 'out', 'bit', 'id'],
    'decl': ['in', 'out', 'bit'],
    'assign': ['id'],
}


class SyntacticalError(Exception):
    def __init__(self, message):
        self.message = message

    def __str__(self):
        return f'Syntactical Error: {self.message}'


class Parser:
    """ Syntactical Parser for Flooat Language

    Args:
        token_stream (list): List of tokens generated by the lexer
    """

    def __init__(self, token_stream) -> None:
        self.token_stream = token_stream
        self.ast = None
        self.current_token = self.token_stream.pop(0)

        self.parse()

    def advance(self):
        self.current_token = self.token_stream.pop(0)

    def get_current_token(self):
        return self.current_token

    def match_label(self, expected_label):
        token = self.get_current_token()

        if token.label != expected_label:
            raise SyntacticalError(f'Unexpected Token. Expected \'{expected_label}\'. Got \'{token.label}\'.')

    def parse(self):
        self.ast = self.mod()

    # Syntactical Rules:

    #* mod = {comp};
    def mod(self):
        mod = Mod()

        while self.get_current_token().label in FIRST_SETS['comp']:
            mod.add_comp(self.comp())

        self.match_label('EOF')

        return mod

    #* comp = ['main'], 'comp', ID, '{', {stmt}, '}';
    def comp(self):
        comp = Comp()

        if self.get_current_token().label == 'main':
            comp.is_main = True
            self.advance()

        self.match_label('comp')
        self.advance()
        self.match_label('id')
        comp.id = self.get_current_token().lexeme
        self.advance()
        self.match_label('l_brace')
        self.advance()

        while self.get_current_token().label in FIRST_SETS['stmt']:
            comp.add_stmt(self.stmt())

        self.match_label('r_brace')
        self.advance()

        return comp

    #* stmt = decl | assign;
    def stmt(self):
        if (label := self.get_current_token().label) in FIRST_SETS['decl']:
            return self.decl()
        elif label in FIRST_SETS['assign']:
            return self.assign()

    #* decl = {'in' | 'out'}, 'bit', ID, ';';
    def decl(self):
        declaration = Decl()

        if self.get_current_token().label == 'in':
            declaration.conn = -1
            self.advance()
        elif self.get_current_token().label == 'out':
            declaration.conn = 1
            self.advance()

        self.match_label('bit')
        declaration.type = 'bit'
        self.advance()
        self.match_label('id')
        declaration.id = self.get_current_token().lexeme
        self.advance()
        self.match_label('semicolon')
        self.advance()

        return declaration
    
    #* assign = ID, '=', expr, ';';
    def assign(self):
        assign = Assign()

        self.match_label('id')
        assign.dt = Identifier(self.get_current_token().lexeme)
        self.advance()
        self.match_label('assign')
        self.advance()
        assign.expr = self.expr()
        self.match_label('semicolon')
        self.advance()

        return assign

    #* expr = term, expr_dash;
    def expr(self):
        l_expr = self.term()

        if self.get_current_token().label in ['or', 'nor']:
            binaryOp = self.expr_dash()
            binaryOp.l_expr = l_expr
            return binaryOp
        else:
            return l_expr
        
    #* expr_dash = ('or' | 'nor'), term, expr_dash | ε;
    def expr_dash(self):
        if (token_label := self.get_current_token().label) == 'or':
            op = token_label
            self.advance()
        
        elif token_label == 'nor':
            op = token_label
            self.advance()
        
        else:
            raise SyntacticalError('Unexpected Token. Expected \'or\' or \'nor\'.')
        
        l_son = self.term()

        if self.get_current_token().label in ['or', 'nor']:
            child_node = self.expr_dash()
            child_node.l_expr = l_son
            node = BinaryOp(None, op, child_node)
            return node
        else:
            # No more operators, create the current node
            return BinaryOp(None, op, l_son)
        
    #* term = factor, term*;
    def term(self):
        l_expr = self.factor()

        if self.get_current_token().label in ['xor', 'xnor']:
            binaryOp = self.term_dash()
            binaryOp.l_expr = l_expr
            return binaryOp
        else:
            return l_expr
    
    #* term_dash = ('xor' | 'xnor'), factor, term_dash | ε;
    def term_dash(self):
        if (token_label := self.get_current_token().label) == 'xor':
            op = token_label
            self.advance()
        
        elif token_label == 'xnor':
            op = token_label
            self.advance()
        
        else:
            raise SyntacticalError('Unexpected Token. Expected \'xor\' or \'xnor\'.')
        
        l_son = self.factor()

        if self.get_current_token().label in ['xor', 'xnor']:
            child_node = self.term_dash()
            child_node.l_expr = l_son
            node = BinaryOp(None, op, child_node)
            return node
        else:
            # Sem mais operadores, criar o nó atual
            return BinaryOp(None, op, l_son)

    #* factor = primary, factor*;
    def factor(self):
        l_expr = self.primary()

        if self.get_current_token().label in ['and', 'nand']:
            binaryOp = self.factor_dash()
            binaryOp.l_expr = l_expr
            return binaryOp
        else:
            return l_expr

    #* factor* = ('and' | 'nand'), primary, factor* | ε;
    def factor_dash(self) -> BinaryOp:
        if (token_label := self.get_current_token().label) == 'and':
            op = token_label
            self.advance()
        
        elif token_label == 'nand':
            op = token_label
            self.advance()
        
        else:
            raise SyntacticalError('Unexpected Token. Expected \'and\' or \'nand\'.')
        
        primary = self.primary()

        if self.get_current_token().label in ['and', 'nand']:
            child_node = self.factor_dash()
            child_l_son = primary
            child_node.l_expr = child_l_son
            node = BinaryOp(None, op, child_node)
            
            return node
        else:
            return BinaryOp(None, op, primary)

    #* primary = 'not', primary | '(', expr, ')' | ID | BIN ;
    def primary(self):
        if (token_label := self.get_current_token().label) == 'id':
            binary = Identifier(self.get_current_token().lexeme)
            self.advance()

            return binary

        elif token_label == 'bin':
            value = self.get_current_token().lexeme
            self.advance()

            return Binary(value)

        elif token_label == 'not':
            op = self.get_current_token().lexeme
            self.advance()

            return UnaryOp(op, self.primary())

        elif token_label == 'l_paren':
            self.advance()
            expr = self.expr()
            self.match_label('r_paren')
            self.advance()

            return expr
