import re
from unittest.mock import mock_open, patch

import pytest

from flote.simulation import eval_nodes
from flote.simulation.buses import BitBus, BitBusValue
from flote.simulation.component import Component
from flote.testbench import TestBench as FloteTestBench


def make_bit_bus(
    id_: str,
    value: list[bool] | None = None,
    msb_descending: bool = False,
) -> BitBus:
    bus = BitBus()
    bus.id = id_
    bus.value = BitBusValue(value)
    bus.msb_descending = msb_descending
    return bus


def make_component() -> Component:
    component = Component("Top")
    a = make_bit_bus("a")
    y = make_bit_bus("y")

    y.assignment = eval_nodes.Ref(a, None, None)
    a.influence_list.append(y)
    component.buses = {"a": a, "y": y}

    return component


def signal_values(tb: FloteTestBench) -> dict[str, str]:
    assert tb.samples
    return {signal.id: signal.value for signal in tb.samples[-1].signals}


def test_wait_accumulates_simulation_time():
    tb = FloteTestBench(make_component())

    tb.wait(5)
    tb.wait(7)

    assert tb.s_time == 12


def test_sets_valid_time_unit_and_rejects_invalid_time_unit():
    tb = FloteTestBench(make_component())

    tb.set_time_unit("ps")

    assert tb.time_unit == "ps"
    with pytest.raises(ValueError, match="Invalid time unit"):
        tb.set_time_unit("minute")


def test_update_records_sample_after_stabilizing_component():
    tb = FloteTestBench(make_component())

    tb.update({"a": "1"})

    assert len(tb.samples) == 1
    assert tb.samples[0].time == 0
    assert signal_values(tb) == {"a": "1", "y": "1"}


def test_update_records_samples_at_current_time():
    tb = FloteTestBench(make_component())

    tb.update({"a": "1"})
    tb.wait(10)
    tb.update({"a": "0"})

    assert [sample.time for sample in tb.samples] == [0, 10]
    assert signal_values(tb) == {"a": "0", "y": "0"}


def test_dump_vcd_without_samples_uses_current_component_values():
    component = Component("Top")
    component.buses = {
        "a": make_bit_bus("a", [True]),
        "bus": make_bit_bus("bus", [True, False, True]),
        "down": make_bit_bus("down", [False, True], msb_descending=True),
    }
    tb = FloteTestBench(component)
    tb.set_time_unit("us")
    tb.wait(3)

    vcd = tb.dump_vcd()

    assert "$version Generated by Flote v1.0.0 - Bilu $end" in vcd
    assert re.search(r"\$date \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} \$end", vcd)
    assert "$timescale 1 us $end" in vcd
    assert "$scope module Top $end" in vcd
    assert "$var wire 1 ! a $end" in vcd
    assert "$var wire 3 \" bus[0:2] $end" in vcd
    assert "$var wire 2 # down[1:0] $end" in vcd
    assert "$dumpvars\n1!\nb101 \"\nb01 #\n$end\n#3\n" in vcd


def test_dump_vcd_writes_nested_scopes_and_only_value_changes():
    component = Component("Top")
    component.buses = {
        "child.a": make_bit_bus("child.a", [False]),
        "child.y": make_bit_bus("child.y", [False]),
    }
    tb = FloteTestBench(component)

    tb.update({"child.a": "1"})
    tb.wait(5)
    tb.update({"child.a": "1"})
    tb.wait(5)
    tb.update({"child.a": "0"})

    vcd = tb.dump_vcd()

    assert "\t$scope module child $end" in vcd
    assert "\t\t$var wire 1 ! a $end" in vcd
    assert "\t\t$var wire 1 \" y $end" in vcd
    assert "$dumpvars\n1!\n0\"\n$end\n" in vcd
    assert "#0\n0!\n" not in vcd
    assert "#5\n" not in vcd
    assert "#10\n0!\n" in vcd


def test_save_vcd_writes_dump_to_file():
    tb = FloteTestBench(make_component())
    expected_vcd = tb.dump_vcd()

    with patch("builtins.open", mock_open()) as mocked_open:
        tb.save_vcd("waves.vcd")

    mocked_open.assert_called_once_with("waves.vcd", "w")
    mocked_open().write.assert_called_once_with(expected_vcd)
