"""
This module have classes responsible for registering the signals values and
controlling time in them simulation.
"""
from datetime import datetime

from .simulation.python.core.component import Component as PythonComponent
from .simulation.rust.core import Component as RustComponent

VERSION = '0.4.0'
CODENAME = 'Gambiarra'
VALID_UNITS = ['fs', 'ps', 'ns', 'us', 'ms', 's']


class Signal:
    """
    This class represents a signal in the simulation.
    """
    def __init__(self, id: str, value: str) -> None:
        self.id = id
        self.value = value

    def __repr__(self) -> str:
        return f'Signal {self.id}: {self.value}'


class WaveSample:
    """
    This class represents a sample of the waves generated by the circuit.
    """
    def __init__(self, time, signals):
        self.time = time

        # signals is a tuple of signal name and value
        self.signals: list[Signal] = signals


class TestBench:
    def __init__(self, component: PythonComponent | RustComponent) -> None:
        self.s_time: int = 0
        self.time_unit: str = 'ns'
        self.samples: list[WaveSample] = []
        self.component = component

    def __str__(self) -> str:
        return self.component.__str__()

    def wait(self, time: int) -> None:
        """This method waits for a certain time."""
        self.s_time += time

    def set_time_unit(self, time_unit: str) -> None:
        if time_unit not in VALID_UNITS:
            raise ValueError(
                f'Invalid time unit "{time_unit}". Valid units are: '
                f'{VALID_UNITS}'
            )

        else:
            self.time_unit = time_unit

    def dump_vcd(self):
        header_metadata = '' \
            f'$version Generated by Flote v{VERSION} - {CODENAME} $end\n' \
            f'$date {datetime.now().strftime(r"%Y-%m-%d %H:%M:%S")} $end\n' \
            f'$timescale 1{self.time_unit} $end\n'

        header_metadata += '\n$comment Hello from Theresina. $end\n'

        header_declaration = f'\n$scope module {self.component.id_} $end\n'

        # Check which backend is being used
        is_rust = isinstance(self.component, RustComponent)

        bus_meta: dict[str, tuple[str, int, bool]] = {}
        if is_rust:
            # Rust backend: busses_info is Dict[str, Tuple[str, bool]]
            buses_info = self.component.busses_info
            for bit_name, (bit_value, msb_descending) in buses_info.items():
                width = len(bit_value)
                bus_meta[bit_name] = (bit_value, width, msb_descending)
                bit_ref = bit_name
                if width > 1:
                    if msb_descending:
                        bit_ref = f'{bit_name}[{width - 1}:0]'
                    else:
                        bit_ref = f'{bit_name}[0:{width - 1}]'
                header_declaration += (
                    f'\t$var wire {width} {bit_name} {bit_ref} $end\n'
                )
        else:
            # Python backend: buses is Dict[str, BaseBus]
            for bit_name, bit_bus in self.component.buses.items():
                width = len(bit_bus.value.raw_value)
                bit_value = bit_bus.get_vcd_repr()
                msb_descending = bit_bus.msb_descending
                bus_meta[bit_name] = (bit_value, width, msb_descending)
                bit_ref = bit_name
                if width > 1:
                    if bit_bus.msb_descending:
                        bit_ref = f'{bit_name}[{width - 1}:0]'
                    else:
                        bit_ref = f'{bit_name}[0:{width - 1}]'
                header_declaration += (
                    f'\t$var wire {width} {bit_name} {bit_ref} $end\n'
                )

        header_declaration += '$upscope $end\n\n'

        header = (
            header_metadata +
            header_declaration +
            '$enddefinitions $end\n'
        )

        datasec = ''

        def format_value(value: str, width: int, identifier: str) -> str:
            if width == 1:
                return f"{value} {identifier}\n"
            return f"b{value} {identifier}\n"

        # Initial dumpvars
        initial_signals = None
        if self.samples:
            initial_signals = {sig.id: sig.value for sig in self.samples[0].signals}
        else:
            initial_signals = {name: meta[0] for name, meta in bus_meta.items()}

        datasec += "\n$dumpvars\n"
        for bit_name in sorted(bus_meta.keys()):
            value, width, _ = bus_meta[bit_name]
            if initial_signals is not None and bit_name in initial_signals:
                value = initial_signals[bit_name]
            datasec += format_value(value, width, bit_name)
        datasec += "$end\n"

        for sample in self.samples:
            datasec += f"\n#{sample.time}\n\n"

            for signal in sample.signals:
                width = bus_meta.get(signal.id, ("", 1, False))[1]
                datasec += format_value(signal.value, width, signal.id)

        return header + datasec + f'\n#{self.s_time}\n'

    def save_vcd(self, file_path: str) -> None:
        """This method saves the vcd file."""
        with open(file_path, 'w') as f:
            f.write(self.dump_vcd())
            f.close()

    def update(self, new_values: dict[str, str]) -> None:
        # Check which backend is being used
        is_rust = isinstance(self.component, RustComponent)
        if is_rust:
            # Rust backend: busses is Dict[str, str]
            assert isinstance(self.component, RustComponent)
            sample = WaveSample(self.s_time, [])
            self.component.update_and_get(new_values)
            buses_dict = self.component.busses
            for id, value in buses_dict.items():
                sample.signals.append(Signal(id, value))
        else:
            # Python backend: buses is Dict[str, BaseBus]
            sample = WaveSample(self.s_time, [])
            self.component.update_signals(new_values)
            for id, bus in self.component.buses.items():
                sample.signals.append(Signal(id, bus.get_vcd_repr()))

        self.samples.append(sample)
