"""
This module have classes responsible for registering the signals values and
controlling time in them simulation.
"""
from datetime import datetime

from .simulation.python.core.component import Component as PythonComponent
from .simulation.rust.core import Component as RustComponent

VERSION = '0.4.0'
CODENAME = 'Gambiarra'
VALID_UNITS = ['fs', 'ps', 'ns', 'us', 'ms', 's']


class Signal:
    """
    This class represents a signal in the simulation.
    """
    def __init__(self, id: str, value: str) -> None:
        self.id = id
        self.value = value

    def __repr__(self) -> str:
        return f'Signal {self.id}: {self.value}'


class WaveSample:
    """
    This class represents a sample of the waves generated by the circuit.
    """
    def __init__(self, time, signals):
        self.time = time

        # signals is a tuple of signal name and value
        self.signals: list[Signal] = signals


class TestBench:
    def __init__(self, component: PythonComponent | RustComponent) -> None:
        self.s_time: int = 0
        self.time_unit: str = 'ns'
        self.samples: list[WaveSample] = []
        self.component = component

    def __str__(self) -> str:
        return self.component.__str__()

    def wait(self, time: int) -> None:
        """This method waits for a certain time."""
        self.s_time += time

    def set_time_unit(self, time_unit: str) -> None:
        if time_unit not in VALID_UNITS:
            raise ValueError(
                f'Invalid time unit "{time_unit}". Valid units are: '
                f'{VALID_UNITS}'
            )

        else:
            self.time_unit = time_unit

    def _get_vcd_symbol(self, index: int) -> str:
        """Generates a valid VCD symbol for a given integer index."""
        symbol = ""
        while True:
            symbol = chr(33 + (index % 94)) + symbol
            index //= 94
            if index == 0:
                break
        return symbol

    def dump_vcd(self) -> str:
        header_metadata = (
            f'$version Generated by Flote v{VERSION} - {CODENAME} $end\n'
            f'$date {datetime.now().strftime(r"%Y-%m-%d %H:%M:%S")} $end\n'
            f'$timescale 1 {self.time_unit} $end\n'
        )

        # Check which backend is being used
        is_rust = isinstance(self.component, RustComponent)

        # Store metadata including the generated symbol
        # name -> (initial_value, width, msb_descending, symbol)
        bus_meta: dict[str, tuple[str, int, bool, str]] = {}

        class ScopeNode:
            def __init__(self, name: str):
                self.name = name
                self.children: dict[str, 'ScopeNode'] = {}
                self.signals: list[tuple[str, int, bool, str]] = []

        root = ScopeNode(self.component.id_)

        def add_signal(bit_name: str, bit_value: str, width: int, msb_descending: bool, symbol_idx: int):
            symbol = self._get_vcd_symbol(symbol_idx)
            bus_meta[bit_name] = (bit_value, width, msb_descending, symbol)

            parts = bit_name.split('.')
            current = root
            for part in parts[:-1]:
                if part not in current.children:
                    current.children[part] = ScopeNode(part)
                current = current.children[part]
            current.signals.append((parts[-1], width, msb_descending, symbol))

        if is_rust:
            buses_info = self.component.busses_info
            for i, (bit_name, (bit_value, msb_descending)) in enumerate(buses_info.items()):
                width = len(bit_value)
                add_signal(bit_name, bit_value, width, msb_descending, i)
        else:
            for i, (bit_name, bit_bus) in enumerate(self.component.buses.items()):
                width = len(bit_bus.value.raw_value)
                bit_value = bit_bus.get_vcd_repr()
                msb_descending = bit_bus.msb_descending
                add_signal(bit_name, bit_value, width, msb_descending, i)

        def write_scope(node: ScopeNode, level: int = 0) -> str:
            indent = "\t" * level
            res = f"{indent}$scope module {node.name} $end\n"
            for short_name, width, msb_descending, symbol in node.signals:
                bit_ref = short_name
                if width > 1:
                    if msb_descending:
                        bit_ref = f'{short_name}[{width - 1}:0]'
                    else:
                        bit_ref = f'{short_name}[0:{width - 1}]'
                res += f"{indent}\t$var wire {width} {symbol} {bit_ref} $end\n"
            for child in node.children.values():
                res += write_scope(child, level + 1)
            res += f"{indent}$upscope $end\n"
            return res

        header_declaration = write_scope(root) + '$enddefinitions $end\n'

        header = header_metadata + header_declaration

        def format_value(value: str, width: int, symbol: str) -> str:
            if width == 1:
                return f"{value}{symbol}\n"  # No space for single bit
            return f"b{value} {symbol}\n"

        # Determine initial dumpvars
        initial_signals = {}
        if self.samples:
            initial_signals = {sig.id: sig.value for sig in self.samples[0].signals}
        else:
            initial_signals = {name: meta[0] for name, meta in bus_meta.items()}

        datasec = "$dumpvars\n"
        last_values = {}
        for bit_name in sorted(bus_meta.keys()):
            _, width, _, symbol = bus_meta[bit_name]
            value = initial_signals.get(bit_name, bus_meta[bit_name][0])
            datasec += format_value(value, width, symbol)
            last_values[bit_name] = value
        datasec += "$end\n"

        # Dump simulation samples (only changes)
        last_time = -1
        for sample in self.samples:
            changes = []
            for signal in sample.signals:
                if signal.id not in bus_meta:
                    continue
                if last_values.get(signal.id) != signal.value:
                    _, width, _, symbol = bus_meta[signal.id]
                    changes.append(format_value(signal.value, width, symbol))
                    last_values[signal.id] = signal.value

            if changes and sample.time > last_time:
                datasec += f"#{sample.time}\n"
                datasec += "".join(changes)
                last_time = sample.time

        if self.s_time > last_time:
             datasec += f"#{self.s_time}\n"

        return header + datasec

    def save_vcd(self, file_path: str) -> None:
        """This method saves the vcd file."""
        with open(file_path, 'w') as f:
            f.write(self.dump_vcd())
            f.close()

    def update(self, new_values: dict[str, str]) -> None:
        # Check which backend is being used
        is_rust = isinstance(self.component, RustComponent)
        if is_rust:
            # Rust backend: busses is Dict[str, str]
            assert isinstance(self.component, RustComponent)
            sample = WaveSample(self.s_time, [])
            self.component.update_and_get(new_values)
            buses_dict = self.component.busses
            for id, value in buses_dict.items():
                sample.signals.append(Signal(id, value))
        else:
            # Python backend: buses is Dict[str, BaseBus]
            sample = WaveSample(self.s_time, [])
            self.component.update_signals(new_values)
            for id, bus in self.component.buses.items():
                sample.signals.append(Signal(id, bus.get_vcd_repr()))

        self.samples.append(sample)
